src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $usertype = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\OneToMany(targetEntity: Blog::class, mappedBy: 'author')]
    private Collection $blogs;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    public function __construct()
    {
        $this->blogs = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getFullname();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->first_name .' '. $this->last_name;
    }

    public function getAvatarUri(): ?string
    {
        return $this->profile_picture;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): static
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getUsertype(): ?string
    {
        return $this->usertype;
    }

    public function setUsertype(?string $usertype): static
    {
        $this->usertype = $usertype;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Blog>
     */
    public function getBlogs(): Collection
    {
        return $this->blogs;
    }

    public function addBlog(Blog $blog): static
    {
        if (!$this->blogs->contains($blog)) {
            $this->blogs->add($blog);
            $blog->setAuthor($this);
        }

        return $this;
    }

    public function removeBlog(Blog $blog): static
    {
        if ($this->blogs->removeElement($blog)) {
            // set the owning side to null (unless already changed)
            if ($blog->getAuthor() === $this) {
                $blog->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): static
    {
        $this->about = $about;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Repository\ContentRepository;
use App\Repository\ImageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/security/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils, ContentRepository $contentRepository, ImageRepository $imageRepository): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('admin');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        $all_content = $contentRepository->findAll();
        $all_images = $imageRepository->findAll();
        $content = [];
        $images = [];

        foreach ($all_content as $item) {
            $content[$item->getDescription()] = $item;
        }
        foreach ($all_images as $item) {
            $images[$item->getSlug()] = $item;
        }


        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername, 
            'error' => $error,
            'content' => $content,
            'images' => $images
        ]);
    }

    #[Route(path: '/security/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block page %}

	<!-- breadcrumb -->
	<div class="site-breadcrumb" style="background: url(/site/assets/img/breadcrumb/gybird-motors-car-1.jpg)">
		<div class="container">
			<h2 class="breadcrumb-title">Login</h2>
			<ul class="breadcrumb-menu">
				<li><a href="{{ path('app_index') }}">Home</a></li>
				<li class="active">Login</li>
			</ul>
		</div>
	</div>
	<!-- breadcrumb end -->


	<!-- login area -->
	<div class="login-area py-120">
		<div class="container">
			<div class="col-md-5 mx-auto">
				<div class="login-form">
					<div class="login-header">
						<img src="assets/img/logo/logo.png" alt="">
						<p>Login to your Gybird Account</p>
						{% if error %}
						<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
						{% endif %}
						{% if app.user %}
						<div class="alert alert-info">
							You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
						</div>
						{% endif %}
					</div>
					<form method="POST">
						<div class="form-group">
							<label>Email Address</label>
							<input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="password" name="password" id="inputPassword" class="form-control" placeholder="********" autocomplete="current-password" required>
						</div>
						<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">								
						<div class="d-flex justify-content-between mb-4">
							<div class="form-check">
								<input class="form-check-input" name="_remember_me" type="checkbox" value="" id="remember">
								<label class="form-check-label" for="remember">
									Remember Me
								</label>
							</div>
									<a href="{{path('app_forgot_password_request')}}" class="switcher-text">Forgot Password</a>
						</div>
						<div class="d-flex align-items-center">
							<button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Login</button>
						</div>
					</form>
					<div class="login-footer">
						<p>Don't have an account? <a href="{{path('app_register')}}">Register.</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- login area end -->

{% endblock %}