src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $engine_capacity = null;
    #[ORM\Column(nullable: true)]
    private ?int $horsepower = null;

    #[ORM\Column(nullable: true)]
    private ?int $torque = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $price_guide = null;

    #[ORM\Column(nullable: true)]
    private ?bool $sunroof = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $features = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dimensions = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $zero_to_hundred_time = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $yom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\OneToMany(targetEntity: CarImages::class, mappedBy: 'car')]
    private Collection $carImages;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_url = null;

    #[ORM\Column(nullable: true)]
    private ?int $listing_position = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $transparent_bg_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $used = null;

    #[ORM\ManyToMany(targetEntity: CarCategory::class, mappedBy: 'cars')]
    private Collection $carCategories;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?CarMake $carMake = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?DriveType $driveType = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?FuelType $fuelType = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Transmission $transmission = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?CarModel $carModel = null;

    public function __construct()
    {
        $this->carImages = new ArrayCollection();
        $this->carCategories = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->carMake . " " . $this->carModel . " - " . $this->yom . " " . $this->engine_capacity . "cc " . $this->fuelType;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEngineCapacity(): ?int
    {
        return $this->engine_capacity;
    }

    public function setEngineCapacity(?int $engine_capacity): static
    {
        $this->engine_capacity = $engine_capacity;

        return $this;
    }

    public function getHorsepower(): ?int
    {
        return $this->horsepower;
    }

    public function setHorsepower(?int $horsepower): static
    {
        $this->horsepower = $horsepower;

        return $this;
    }

    public function getTorque(): ?int
    {
        return $this->torque;
    }

    public function setTorque(?int $torque): static
    {
        $this->torque = $torque;

        return $this;
    }

    public function getPriceGuide(): ?string
    {
        return $this->price_guide;
    }

    public function setPriceGuide(?string $price_guide): static
    {
        $this->price_guide = $price_guide;

        return $this;
    }

    public function isSunroof(): ?bool
    {
        return $this->sunroof;
    }

    public function setSunroof(?bool $sunroof): static
    {
        $this->sunroof = $sunroof;

        return $this;
    }

    public function getFeatures(): ?string
    {
        return $this->features;
    }

    public function setFeatures(?string $features): static
    {
        $this->features = $features;

        return $this;
    }

    public function getDimensions(): ?string
    {
        return $this->dimensions;
    }

    public function setDimensions(?string $dimensions): static
    {
        $this->dimensions = $dimensions;

        return $this;
    }

    public function getZeroToHundredTime(): ?string
    {
        return $this->zero_to_hundred_time;
    }

    public function setZeroToHundredTime(?string $zero_to_hundred_time): static
    {
        $this->zero_to_hundred_time = $zero_to_hundred_time;

        return $this;
    }

    public function getYom(): ?string
    {
        return $this->yom;
    }

    public function setYom(?string $yom): static
    {
        $this->yom = $yom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, CarImages>
     */
    public function getCarImages(): Collection
    {
        return $this->carImages;
    }

    public function addCarImage(CarImages $carImage): static
    {
        if (!$this->carImages->contains($carImage)) {
            $this->carImages->add($carImage);
            $carImage->setCar($this);
        }

        return $this;
    }

    public function removeCarImage(CarImages $carImage): static
    {
        if ($this->carImages->removeElement($carImage)) {
            // set the owning side to null (unless already changed)
            if ($carImage->getCar() === $this) {
                $carImage->setCar(null);
            }
        }

        return $this;
    }

    public function getVideoUrl(): ?string
    {
        return $this->video_url;
    }

    public function setVideoUrl(?string $video_url): static
    {
        $this->video_url = $video_url;

        return $this;
    }

    public function getListingPosition(): ?int
    {
        return $this->listing_position;
    }

    public function setListingPosition(?int $listing_position): static
    {
        $this->listing_position = $listing_position;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTransparentBgImage(): ?string
    {
        return $this->transparent_bg_image;
    }

    public function setTransparentBgImage(?string $transparent_bg_image): static
    {
        $this->transparent_bg_image = $transparent_bg_image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function isUsed(): ?bool
    {
        return $this->used;
    }

    public function setUsed(?bool $used): static
    {
        $this->used = $used;

        return $this;
    }

    /**
     * @return Collection<int, CarCategory>
     */
    public function getCarCategories(): Collection
    {
        return $this->carCategories;
    }

    public function addCarCategory(CarCategory $carCategory): static
    {
        if (!$this->carCategories->contains($carCategory)) {
            $this->carCategories->add($carCategory);
            $carCategory->addCar($this);
        }

        return $this;
    }

    public function removeCarCategory(CarCategory $carCategory): static
    {
        if ($this->carCategories->removeElement($carCategory)) {
            $carCategory->removeCar($this);
        }

        return $this;
    }

    public function getCarMake(): ?CarMake
    {
        return $this->carMake;
    }

    public function setCarMake(?CarMake $carMake): static
    {
        $this->carMake = $carMake;

        return $this;
    }

    public function getDriveType(): ?DriveType
    {
        return $this->driveType;
    }

    public function setDriveType(?DriveType $driveType): static
    {
        $this->driveType = $driveType;

        return $this;
    }

    public function getFuelType(): ?FuelType
    {
        return $this->fuelType;
    }

    public function setFuelType(?FuelType $fuelType): static
    {
        $this->fuelType = $fuelType;

        return $this;
    }

    public function getTransmission(): ?Transmission
    {
        return $this->transmission;
    }

    public function setTransmission(?Transmission $transmission): static
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getCarModel(): ?CarModel
    {
        return $this->carModel;
    }

    public function setCarModel(?CarModel $carModel): static
    {
        $this->carModel = $carModel;

        return $this;
    }


}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $template_path = null;

    #[ORM\Column(nullable: true)]
    private ?int $priority = null;

    #[ORM\ManyToMany(targetEntity: Page::class, mappedBy: 'sections')]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->description;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTemplatePath(): ?string
    {
        return $this->template_path;
    }

    public function setTemplatePath(?string $template_path): static
    {
        $this->template_path = $template_path;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection<int, Page>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->addSection($this);
        }

        return $this;
    }

    public function removePage(Page $page): static
    {
        if ($this->pages->removeElement($page)) {
            $page->removeSection($this);
        }

        return $this;
    }
}

templates/index/_car_card.html.twig
<style>
.car-card-item {
    display: flex;
    flex-direction: column; /* Stacks on small screens */
}

@media (min-width: 768px) {
    .car-card-item {
        flex-direction: row; /* Side-by-side on medium+ screens */
        gap: 20px; /* Adds spacing between car-card-img and car-card-content */
    }

    .car-card-img {
        width: 40%; /* Adjust width as needed */
    }

    .car-card-content {
        width: 60%; /* Adjust width as needed */
    }
}
</style>
<div class="col-12">
    <div class="car-card-item d-flex align-items-start flex-column flex-md-row">
        <!-- Car Image -->
        <div class="car-card-img flex-shrink-0">
            <span class="car-status status-1">{{ car.used ? 'Japan Used' : 'Brand New' }}</span>
            <img src="/site/images/car_images/{{ car.image }}" alt="">
            <div class="car-btns">
                <a href="#"><i class="far fa-heart"></i></a>
                <a href="#"><i class="far fa-arrows-repeat"></i></a>
            </div>
        </div>

        <!-- Car Content -->
        <div class="car-card-content flex-grow-1 ms-md-4">
            <div class="car-top">
                <h4><a href="{{ path('car_detail', {'slug': car.slug }) }}">{{ car }}</a></h4>
            </div>
            <ul class="car-list">
                <li><i class="far fa-steering-wheel"></i>{{ car.transmission }}</li>
                <li><i class="far fa-road"></i>{{ car.fuelType }}</li>
                <li><i class="far fa-car"></i>{{ car.yom }}</li>
                <li><i class="fa-solid fa-engine"></i>{{ car.engineCapacity }} cc</li>
                <li class="d-inline-flex align-items-center">
                    <h5>Loan Calculator:</h5>
                    <div class="btn-group ms-2" role="group">
                        <a class="btn btn-sm btn-primary" href="{{ path('app_page', {'page': 'car-loan-calculator', 'carPrice': car.priceGuide, 'loanTerm': 60, 'loanRate': 18.7, 'cqp': car.id, 'type': 'salary'}) }}">
                            Salaried
                        </a>
                        <a class="btn btn-sm btn-info" href="{{ path('app_page', {'page': 'car-loan-calculator', 'carPrice': car.priceGuide, 'loanTerm': 48, 'loanRate': 23.7, 'cqp': car.id, 'type': 'business'}) }}">
                            Business
                        </a>
                    </div>
                </li>                                            
            </ul>
            <p>
                {{ car.description | slice(0, 300) | raw }}...
            </p>
            <div class="car-card-footer">
                <span class="car-card-price">KSh {{ car.priceGuide | number_format }}</span>
                <a href="{{ path('car_detail', {'slug': car.slug }) }}" class="theme-btn"><span class="far fa-eye"></span>Details</a>
            </div>
        </div>
    </div>
</div>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block page %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}

	{% for section in sortedSections %}	
	{{ include('sections/' ~ section.templatePath) }}
	{% endfor %}

{% endblock %}

templates/index/page.html.twig
{% extends 'base.html.twig' %}
{% if myseo is defined and myseo is not null %}
{% set title = myseo.metaTitle %}
{% set meta_desc = myseo.metaDescription %}
{% else %}
{% set title = page.metaTitle %}
{% set meta_desc = page.metaDescription %}
{% endif %}
{% block meta_description %}{{meta_desc}}{% endblock %}

{% block meta_title %}{{ title }}{% endblock %}
{% block page %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% if page.pageContent|length > 1 %}
        {% include('sections/variable_banner.html.twig') %}
        {% if page.contentFirst %}
            {% include ('sections/service.html.twig') %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
        {% else %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
            {% include ('sections/service.html.twig') %}
        {% endif %}
    {% else %}
        {% for section in sortedSections %}
            {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}    
    {% endif %}

{% endblock %}

templates/index/service.html.twig
{% extends 'base.html.twig' %}
{% block meta_description %}{{page.metaDescription}}{% endblock %}
{% block meta_title %}{{page.metaTitle }}{% endblock %}
{% block page %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% include('sections/service_banner.html.twig') %}
    {% if page.contentFirst %}
        {% include ('sections/service.html.twig') %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
    {% else %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
        {% include ('sections/service.html.twig') %}
    {% endif %}

{% endblock %}