src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publication_date = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\ManyToMany(targetEntity: BlogCategory::class, mappedBy: 'blog')]
    private Collection $blogCategories;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_url = null;

    public function __toString(): string
    {
        return (string) $this->title;
    }
    
    public function __construct()
    {
        $this->blogCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(?bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    /**
     * @return Collection<int, BlogCategory>
     */
    public function getBlogCategories(): Collection
    {
        return $this->blogCategories;
    }

    public function addBlogCategory(BlogCategory $blogCategory): static
    {
        if (!$this->blogCategories->contains($blogCategory)) {
            $this->blogCategories->add($blogCategory);
            $blogCategory->addBlog($this);
        }

        return $this;
    }

    public function removeBlogCategory(BlogCategory $blogCategory): static
    {
        if ($this->blogCategories->removeElement($blogCategory)) {
            $blogCategory->removeBlog($this);
        }

        return $this;
    }

    public function getVideoUrl(): ?string
    {
        return $this->video_url;
    }

    public function setVideoUrl(?string $video_url): static
    {
        $this->video_url = $video_url;

        return $this;
    }
}

src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $engine_capacity = null;
    #[ORM\Column(nullable: true)]
    private ?int $horsepower = null;

    #[ORM\Column(nullable: true)]
    private ?int $torque = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $price_guide = null;

    #[ORM\Column(nullable: true)]
    private ?bool $sunroof = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $features = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dimensions = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $zero_to_hundred_time = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $yom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\OneToMany(targetEntity: CarImages::class, mappedBy: 'car')]
    private Collection $carImages;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_url = null;

    #[ORM\Column(nullable: true)]
    private ?int $listing_position = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $transparent_bg_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $used = null;

    #[ORM\ManyToMany(targetEntity: CarCategory::class, mappedBy: 'cars')]
    private Collection $carCategories;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?CarMake $carMake = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?DriveType $driveType = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?FuelType $fuelType = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Transmission $transmission = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?CarModel $carModel = null;

    public function __construct()
    {
        $this->carImages = new ArrayCollection();
        $this->carCategories = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->carMake . " " . $this->carModel . " - " . $this->yom . " " . $this->engine_capacity . "cc " . $this->fuelType;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEngineCapacity(): ?int
    {
        return $this->engine_capacity;
    }

    public function setEngineCapacity(?int $engine_capacity): static
    {
        $this->engine_capacity = $engine_capacity;

        return $this;
    }

    public function getHorsepower(): ?int
    {
        return $this->horsepower;
    }

    public function setHorsepower(?int $horsepower): static
    {
        $this->horsepower = $horsepower;

        return $this;
    }

    public function getTorque(): ?int
    {
        return $this->torque;
    }

    public function setTorque(?int $torque): static
    {
        $this->torque = $torque;

        return $this;
    }

    public function getPriceGuide(): ?string
    {
        return $this->price_guide;
    }

    public function setPriceGuide(?string $price_guide): static
    {
        $this->price_guide = $price_guide;

        return $this;
    }

    public function isSunroof(): ?bool
    {
        return $this->sunroof;
    }

    public function setSunroof(?bool $sunroof): static
    {
        $this->sunroof = $sunroof;

        return $this;
    }

    public function getFeatures(): ?string
    {
        return $this->features;
    }

    public function setFeatures(?string $features): static
    {
        $this->features = $features;

        return $this;
    }

    public function getDimensions(): ?string
    {
        return $this->dimensions;
    }

    public function setDimensions(?string $dimensions): static
    {
        $this->dimensions = $dimensions;

        return $this;
    }

    public function getZeroToHundredTime(): ?string
    {
        return $this->zero_to_hundred_time;
    }

    public function setZeroToHundredTime(?string $zero_to_hundred_time): static
    {
        $this->zero_to_hundred_time = $zero_to_hundred_time;

        return $this;
    }

    public function getYom(): ?string
    {
        return $this->yom;
    }

    public function setYom(?string $yom): static
    {
        $this->yom = $yom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, CarImages>
     */
    public function getCarImages(): Collection
    {
        return $this->carImages;
    }

    public function addCarImage(CarImages $carImage): static
    {
        if (!$this->carImages->contains($carImage)) {
            $this->carImages->add($carImage);
            $carImage->setCar($this);
        }

        return $this;
    }

    public function removeCarImage(CarImages $carImage): static
    {
        if ($this->carImages->removeElement($carImage)) {
            // set the owning side to null (unless already changed)
            if ($carImage->getCar() === $this) {
                $carImage->setCar(null);
            }
        }

        return $this;
    }

    public function getVideoUrl(): ?string
    {
        return $this->video_url;
    }

    public function setVideoUrl(?string $video_url): static
    {
        $this->video_url = $video_url;

        return $this;
    }

    public function getListingPosition(): ?int
    {
        return $this->listing_position;
    }

    public function setListingPosition(?int $listing_position): static
    {
        $this->listing_position = $listing_position;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTransparentBgImage(): ?string
    {
        return $this->transparent_bg_image;
    }

    public function setTransparentBgImage(?string $transparent_bg_image): static
    {
        $this->transparent_bg_image = $transparent_bg_image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function isUsed(): ?bool
    {
        return $this->used;
    }

    public function setUsed(?bool $used): static
    {
        $this->used = $used;

        return $this;
    }

    /**
     * @return Collection<int, CarCategory>
     */
    public function getCarCategories(): Collection
    {
        return $this->carCategories;
    }

    public function addCarCategory(CarCategory $carCategory): static
    {
        if (!$this->carCategories->contains($carCategory)) {
            $this->carCategories->add($carCategory);
            $carCategory->addCar($this);
        }

        return $this;
    }

    public function removeCarCategory(CarCategory $carCategory): static
    {
        if ($this->carCategories->removeElement($carCategory)) {
            $carCategory->removeCar($this);
        }

        return $this;
    }

    public function getCarMake(): ?CarMake
    {
        return $this->carMake;
    }

    public function setCarMake(?CarMake $carMake): static
    {
        $this->carMake = $carMake;

        return $this;
    }

    public function getDriveType(): ?DriveType
    {
        return $this->driveType;
    }

    public function setDriveType(?DriveType $driveType): static
    {
        $this->driveType = $driveType;

        return $this;
    }

    public function getFuelType(): ?FuelType
    {
        return $this->fuelType;
    }

    public function setFuelType(?FuelType $fuelType): static
    {
        $this->fuelType = $fuelType;

        return $this;
    }

    public function getTransmission(): ?Transmission
    {
        return $this->transmission;
    }

    public function setTransmission(?Transmission $transmission): static
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getCarModel(): ?CarModel
    {
        return $this->carModel;
    }

    public function setCarModel(?CarModel $carModel): static
    {
        $this->carModel = $carModel;

        return $this;
    }


}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

templates/sections/article-json-ld.html.twig
<script type='application/ld+json'> 
{
  "@context": "http://www.schema.org",
  "@type": "Article",
  "@id": "https://www.wikidata.org/wiki/Q191067",
  "headline": "{{ blog_post.title }}",
  "alternateName": "{{ blog_post.metaTitle }}",
  "url": "https://gybird.co.ke/post/{{ blog_post.slug }}",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://www.wikidata.org/wiki/Q36774"
  },
  "image": "https://gybird.co.ke/site/images/blog_images/{{ blog_post.featuredImage }}",
  "author": {
    "@type": "Person",
    "name": "{{ blog_post.author }}",
    "url": "https://gybird.co.ke"
  },
  "genre": "{{ blog_post.blogCategories | first . categoryName }}",
  "keywords": "{{ blog_post.title }}",
  "datePublished": "{{ blog_post.publicationDate|date('Y-m-d\\TH:i:sP') }}",
  "description": "{{ blog_post.metaDescription }}",
  "articleBody": "{{ blog_post.content }}"
}
 </script>

templates/sections/blog_article.html.twig
        <!-- blog single area -->
        <div class="blog-single-area pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog-single-wrapper">
                            <div class="blog-single-content">
                                <div class="blog-thumb-img">
                                    <img src="{{ asset('site/images/blog_images/' ~ blog_post.featuredImage ) }}"  alt="{{ blog_post.title }}">
                                </div>
                                <div class="blog-info">
                                    <div class="blog-meta">
                                        <div class="blog-meta-left bg-dark p-2">
                                            <ul>
                                                <li><i class="far fa-user"></i><a href="#">{{ blog_post.author }}</a></li> | 
												<ul>
													{% for category in blog_post.blogCategories %}
														<li>
															<a href="#">{{ category }}</a>
														</li>
													{% endfor %}									
												| 
												</ul>
												<li>{{blog_post.publicationDate|date('d, M Y') }}</li>
                                            </ul>
                                        </div>
                                        <div class="blog-meta-right">
                                             <a href="#" class="share-btn"><i class="far fa-share-alt"></i>Share</a>
                                        </div>
                                    </div>
                                    <div class="blog-details">
                                        <div id="table-of-contents"></div>
                                        <h2 class="blog-details-title mb-20">{{ blog_post.title }}</h2>
										{{ blog_post.content | render_cars  }}
                                        <hr>
										<div class="blog-details-tags pb-20">
											<h5>Tags : </h5>
											<ul>
												{% for category in blog_post.blogCategories %}
													<li>
														<a href="#">{{ category }}</a>
													</li>
												{% endfor %}									
											</ul>
										</div>
                                    </div>
                                    <div class="blog-author">
                                        <div class="blog-author-img">
                                            <img src="/site/images/profile_pictures/{{ blog_post.author.profilePicture }}" alt="{{ blog_post.author }}">
                                        </div>
                                        <div class="author-info">
                                            <h6>Author</h6>
                                            <h3 class="author-name">{{ blog_post.author }}</h3>
                                            <p>{{ blog_post.author.about }}</p>
                                            <div class="author-social">
                                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                                <a href="#"><i class="fab fa-twitter"></i></a>
                                                <a href="#"><i class="fab fa-instagram"></i></a>
                                                <a href="#"><i class="fab fa-whatsapp"></i></a>
                                                <a href="#"><i class="fab fa-youtube"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {# <div class="blog-comments">
                                    <h3>Comments (20)</h3>
                                    <div class="blog-comments-wrapper">
                                        <div class="blog-comments-single">
                                            <img src="assets/img/blog/com-1.jpg" alt="thumb">
                                            <div class="blog-comments-content">
                                                <h5>Jesse Sinkler</h5>
                                                <span><i class="far fa-clock"></i> January 31, 2023</span>
                                                <p>There are many variations of passages the majority have suffered in some injected humour or randomised words which don't look even slightly believable.</p>
                                                <a href="#"><i class="far fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                        <div class="blog-comments-single blog-comments-reply">
                                            <img src="assets/img/blog/com-2.jpg" alt="thumb">
                                            <div class="blog-comments-content">
                                                <h5>Daniel Wellman</h5>
                                                <span><i class="far fa-clock"></i> January 31, 2023</span>
                                                <p>There are many variations of passages the majority have suffered in some injected humour or randomised words which don't look even slightly believable.</p>
                                                <a href="#"><i class="far fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                        <div class="blog-comments-single">
                                            <img src="assets/img/blog/com-3.jpg" alt="thumb">
                                            <div class="blog-comments-content">
                                                <h5>Kenneth Evans</h5>
                                                <span><i class="far fa-clock"></i> January 31, 2023</span>
                                                <p>There are many variations of passages the majority have suffered in some injected humour or randomised words which don't look even slightly believable.</p>
                                                <a href="#"><i class="far fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="blog-comments-form">
                                        <h3>Leave A Comment</h3>
                                        <form action="#">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Your Name*">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <input type="email" class="form-control" placeholder="Your Email*">
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <textarea class="form-control" rows="5" placeholder="Your Comment*"></textarea>
                                                    </div>
                                                    <button type="submit" class="theme-btn">Post Comment <i class="far fa-paper-plane"></i></button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div> #}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <aside class="sidebar">
                            <!-- search-->
                            <div class="widget search">
                                <h5 class="widget-title">Search</h5>
                                <form class="search-form">
                                    <input type="text" class="form-control" placeholder="Search Here...">
                                    <button type="submit"><i class="far fa-search"></i></button>
                                </form>
                            </div>
                            <!-- category -->
                            <div class="widget category">
                                <h5 class="widget-title">Category</h5>
                                <div class="category-list">
								{% for blog_category in blog_categories %}
                                    <a href="#"><i class="far fa-arrow-right"></i>{{ blog_category.categoryName }}<span>({{ blog_category.blog | length }})</span></a>
								{% endfor %}
                                </div>
                            </div>
                            <!-- recent post -->
                            <div class="widget recent-post">
                                <h5 class="widget-title">Recent Posts</h5>
								{% for blog_post in blog_posts %}
                                <div class="recent-post-single">
                                    <div class="recent-post-img">
                                        <img src="{{ asset('site/images/blog_images/' ~ blog_post.featuredImage ) }}" alt="{{ blog_post.title }}">
                                    </div>
                                    <div class="recent-post-bio">
                                        <h6><a href="#">{{ blog_post.title }}</a></h6>
                                        <span><i class="far fa-clock"></i>{{blog_post.publicationDate|date('d, M Y') }}</span>
                                    </div>
                                </div>
								{% endfor %}

                            </div>
                            <!-- social share -->
                            <div class="widget social-share">
                                <h5 class="widget-title">Follow Us</h5>
                                <div class="social-share-link">
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-dribbble"></i></a>
                                    <a href="#"><i class="fab fa-whatsapp"></i></a>
                                    <a href="#"><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                            <!-- Recent Post -->
                            <div class="widget sidebar-tag">
                                <h5 class="widget-title">Popular Tags</h5>
                                <div class="tag-list">
                                    <a href="#">Car</a>
                                    <a href="#">Dealer</a>
                                    <a href="#">Drive</a>
                                    <a href="#">Insurance</a>
                                    <a href="#">Offer</a>
                                    <a href="#">Tips</a>
                                    <a href="#">Maintenance</a>
                                    <a href="#">Luxury</a>
                                </div>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
        <!-- blog single area end --> 

templates/sections/callback.html.twig
	<!-- Subscribe Area Start  -->
	<div class="subscribe-now">
		<div class="container">
			<div class="row subscribe-bg align-items-center">
				<div class="subscribe-shape"></div>
				<div class="col-xl-5 col-lg-5">
					<div class="subscribe-left md-mb-25">
						<h3>Request A Call Back</h3>
					</div>
				</div>
				<div class="col-xl-7 col-lg-7">
					<div class="subscribe-right">
						<form class="subscribe-box" action="#">
							<input class="form-control" placeholder="Phone Number" type="text">
							<button type="submit" class="subscribe-button">Request Now</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Subscribe Area End -->

templates/sections/contact_form.html.twig
{{ render(controller('App\\Controller\\IndexController::renderFooterForm')) }}

templates/sections/local-business-json-ld.html.twig
<script type='application/ld+json'> 
  {
    "@context": "http://www.schema.org",
    "@type": "AutoDealer",
    "name": "Gybird Motors",
    "url": "https://gybird.co.ke",
    "logo": "https://gybird.co.ke/site/images/gybird-logo-long-1725855557.png",
    "image": "https://gybird.co.ke/site/web_images/business-image-1726067373.jpg",
    "description": "{{ seo.metaDescription }}",
    "priceRange": "$$",
    "telephone": "{{ setting.phoneNumber }}",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "{{ setting.businessLocation }}",
      "addressLocality": "Kiambu",
      "addressRegion": "Central",
      "postalCode": "00900",
      "addressCountry": "KE"
    },
    "geo": {
      "latitude": "-1.21605750",
      "@type": "GeoCoordinates",
      "longitude": "36.83305440"
    },
    "hasMap": "https://maps.app.goo.gl/ypHWRgbk9x77mJzp9",
    "openingHours": "Mo, Tu, We, Th, Fr 08:00-18:00",
    "contactPoint": {
      "@type": "ContactPoint",
      "telephone": "0711476249",
      "contactType": "Customer Service"
    }
  }
   </script>

templates/sections/service_banner.html.twig
	<!-- Page Banner Start -->
	<div class="page-banner section-padding" style="background-image: url({{asset('site/images/page_images/' ~ page.featuredImage ) }})">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="page-title">
						<h1 class="pb-30">{{page.heading}}</h1>
						<ul>
							<li><a href="#">Home</a>
							</li>
							<li><a href="#">{{page.heading}}</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Page Banner End -->